### ISSUE TITLE
using the fal proxy in SvelteKit fails if you call locals.auth()

### ISSUE THREAD

**Issue by spullara** [fal-ai/fal-js#107]
It fails when proxying with this error:

```
TypeError: immutable
    at appendHeader (node:internal/deps/undici/undici:8352:15)
    at _Headers.append (node:internal/deps/undici/undici:8554:16)
    at Module.add_cookies_to_headers (/Users/sam/Projects/chatbench-fal/node_modules/@sveltejs/kit/src/runtime/server/cookie.js:260:11)
    at /Users/sam/Projects/chatbench-fal/node_modules/@sveltejs/kit/src/runtime/server/respond.js:338:6
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/sam/Projects/chatbench-fal/node_modules/@sentry/sveltekit/build/cjs/server/handle.js:128:21
    at async instrumentHandle (/Users/sam/Projects/chatbench-fal/node_modules/@sentry/sveltekit/build/cjs/server/handle.js:116:27)
    at async Module.respond (/Users/sam/Projects/chatbench-fal/node_modules/@sveltejs/kit/src/runtime/server/respond.js:327:20)
    at async file:///Users/sam/Projects/chatbench-fal/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:524:22
```

for example, just doing this in hooks causes this 

```typescript
// New handler to check/create customerId
const handleCustomerId: Handle = async ({ event, resolve }) => {
    await event.locals.auth();

    return resolve(event);
}

import { handle as auth } from './auth';
export const handle = sequence(auth, handleCustomerId);
```

**Comment by drochetti** [comment]
Thanks for the report and fix suggestion @spullara 
I opened #109 to address it.

I also released `1.1.1-alpha.0` of the `@fal-ai/server-proxy`. Would you be able to give it a try to confirm it works. That would help as I don't have a Svelte app here with a reproducer ready to go.

**Comment by spullara** [comment]
that version appears to work for me. thanks!

**Comment by drochetti** [comment]
@spullara version `1.1.0` is out
